version: '3.9'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mysql-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  mysql-db:
    image: mysql:8.0
    container_name: mysql-tzinh
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
